spring:
  datasource:
    url: ${db.name}
    username: ${db.user}
    password: ${db.pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: ${mail.host}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true
web:
  filter:
    cors:
      allowed-origins: ${CORS.allowed-origins}
      max-age: 3600
      allowed-methods: "*"
      exposed-headers: "Authorization"
      allowed-headers: "*"








